/*
 * FINBOURNE Identity Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1636
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.identity.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.identity.model.CreateUserRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CreateDomainRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateDomainRequest {
  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  private String domain;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private CreateUserRequest owner;

  public static final String SERIALIZED_NAME_TECHNICAL_CONTACT = "technicalContact";
  @SerializedName(SERIALIZED_NAME_TECHNICAL_CONTACT)
  private CreateUserRequest technicalContact;

  public static final String SERIALIZED_NAME_BILLING_CONTACT = "billingContact";
  @SerializedName(SERIALIZED_NAME_BILLING_CONTACT)
  private CreateUserRequest billingContact;

  public static final String SERIALIZED_NAME_SIGNED_AGREEMENTS = "signedAgreements";
  @SerializedName(SERIALIZED_NAME_SIGNED_AGREEMENTS)
  private List<String> signedAgreements = null;


  public CreateDomainRequest domain(String domain) {
    this.domain = domain; 
    return this;
  }

   /**
   * The name LUSID domain to create
   * @return domain
  **/
  @ApiModelProperty(required = true, value = "The name LUSID domain to create")
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }


  public CreateDomainRequest description(String description) {
    this.description = description; 
    return this;
  }

   /**
   * Optional. Free text description of the domain.
   * @return description
  **/
  @ApiModelProperty(value = "Optional. Free text description of the domain.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public CreateDomainRequest companyName(String companyName) {
    this.companyName = companyName; 
    return this;
  }

   /**
   * The name of the company to which the domain is registered
   * @return companyName
  **/
  @ApiModelProperty(required = true, value = "The name of the company to which the domain is registered")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public CreateDomainRequest owner(CreateUserRequest owner) {
    this.owner = owner; 
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @ApiModelProperty(required = true, value = "")
  public CreateUserRequest getOwner() {
    return owner;
  }

  public void setOwner(CreateUserRequest owner) {
    this.owner = owner;
  }


  public CreateDomainRequest technicalContact(CreateUserRequest technicalContact) {
    this.technicalContact = technicalContact; 
    return this;
  }

   /**
   * Get technicalContact
   * @return technicalContact
  **/
  @ApiModelProperty(value = "")
  public CreateUserRequest getTechnicalContact() {
    return technicalContact;
  }

  public void setTechnicalContact(CreateUserRequest technicalContact) {
    this.technicalContact = technicalContact;
  }


  public CreateDomainRequest billingContact(CreateUserRequest billingContact) {
    this.billingContact = billingContact; 
    return this;
  }

   /**
   * Get billingContact
   * @return billingContact
  **/
  @ApiModelProperty(value = "")
  public CreateUserRequest getBillingContact() {
    return billingContact;
  }

  public void setBillingContact(CreateUserRequest billingContact) {
    this.billingContact = billingContact;
  }


  public CreateDomainRequest signedAgreements(List<String> signedAgreements) {
    this.signedAgreements = signedAgreements; 
    return this;
  }

  public CreateDomainRequest addSignedAgreementsItem(String signedAgreementsItem) {
   
    if (this.signedAgreements == null) {
      this.signedAgreements = new ArrayList<>();
    }
    this.signedAgreements.add(signedAgreementsItem);
    return this;
  }

   /**
   * Optional. If Terms and Conditions agreements have been signed during the sign up process
   * @return signedAgreements
  **/
  @ApiModelProperty(value = "Optional. If Terms and Conditions agreements have been signed during the sign up process")
  public List<String> getSignedAgreements() {
    return signedAgreements;
  }

  public void setSignedAgreements(List<String> signedAgreements) {
    this.signedAgreements = signedAgreements;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDomainRequest {\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    technicalContact: ").append(toIndentedString(technicalContact)).append("\n");
    sb.append("    billingContact: ").append(toIndentedString(billingContact)).append("\n");
    sb.append("    signedAgreements: ").append(toIndentedString(signedAgreements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
