/*
 * FINBOURNE Identity Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1636
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.identity.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.identity.model.ErrorDetail;
import com.finbourne.identity.model.Link;
import com.finbourne.identity.model.UserSummary;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Users directory query response
 */
@ApiModel(description = "Users directory query response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ListUsersResponse {
  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private URI href;

  public static final String SERIALIZED_NAME_VALUES = "values";
  @SerializedName(SERIALIZED_NAME_VALUES)
  private Map<String, UserSummary> values = null;

  public static final String SERIALIZED_NAME_FAILED = "failed";
  @SerializedName(SERIALIZED_NAME_FAILED)
  private Map<String, ErrorDetail> failed = null;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links = null;


  public ListUsersResponse href(URI href) {
    this.href = href; 
    return this;
  }

   /**
   * Uri of this response
   * @return href
  **/
  @ApiModelProperty(value = "Uri of this response")
  public URI getHref() {
    return href;
  }

  public void setHref(URI href) {
    this.href = href;
  }


  public ListUsersResponse values(Map<String, UserSummary> values) {
    this.values = values; 
    return this;
  }

  public ListUsersResponse putValuesItem(String key, UserSummary valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

   /**
   * Successful entities, indexed by their id
   * @return values
  **/
  @ApiModelProperty(value = "Successful entities, indexed by their id")
  public Map<String, UserSummary> getValues() {
    return values;
  }

  public void setValues(Map<String, UserSummary> values) {
    this.values = values;
  }


  public ListUsersResponse failed(Map<String, ErrorDetail> failed) {
    this.failed = failed; 
    return this;
  }

  public ListUsersResponse putFailedItem(String key, ErrorDetail failedItem) {
    if (this.failed == null) {
      this.failed = new HashMap<>();
    }
    this.failed.put(key, failedItem);
    return this;
  }

   /**
   * Failed entities, indexed by their id
   * @return failed
  **/
  @ApiModelProperty(value = "Failed entities, indexed by their id")
  public Map<String, ErrorDetail> getFailed() {
    return failed;
  }

  public void setFailed(Map<String, ErrorDetail> failed) {
    this.failed = failed;
  }


  public ListUsersResponse links(List<Link> links) {
    this.links = links; 
    return this;
  }

  public ListUsersResponse addLinksItem(Link linksItem) {
   
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListUsersResponse {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
