/*
 * FINBOURNE Identity Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2450
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.identity.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * SupportRole
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SupportRole {
  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ROLE_IDENTIFIER = "roleIdentifier";
  @SerializedName(SERIALIZED_NAME_ROLE_IDENTIFIER)
  private Map<String, String> roleIdentifier = null;

  public static final String SERIALIZED_NAME_INTERNAL_IDENTIFIER = "internalIdentifier";
  @SerializedName(SERIALIZED_NAME_INTERNAL_IDENTIFIER)
  private String internalIdentifier;


  public SupportRole label(String label) {
    this.label = label; 
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }


  public SupportRole description(String description) {
    this.description = description; 
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public SupportRole roleIdentifier(Map<String, String> roleIdentifier) {
    this.roleIdentifier = roleIdentifier; 
    return this;
  }

  public SupportRole putRoleIdentifierItem(String key, String roleIdentifierItem) {
    if (this.roleIdentifier == null) {
      this.roleIdentifier = new HashMap<>();
    }
    this.roleIdentifier.put(key, roleIdentifierItem);
    return this;
  }

   /**
   * Get roleIdentifier
   * @return roleIdentifier
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getRoleIdentifier() {
    return roleIdentifier;
  }

  public void setRoleIdentifier(Map<String, String> roleIdentifier) {
    this.roleIdentifier = roleIdentifier;
  }


  public SupportRole internalIdentifier(String internalIdentifier) {
    this.internalIdentifier = internalIdentifier; 
    return this;
  }

   /**
   * Get internalIdentifier
   * @return internalIdentifier
  **/
  @ApiModelProperty(value = "")
  public String getInternalIdentifier() {
    return internalIdentifier;
  }

  public void setInternalIdentifier(String internalIdentifier) {
    this.internalIdentifier = internalIdentifier;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportRole {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    roleIdentifier: ").append(toIndentedString(roleIdentifier)).append("\n");
    sb.append("    internalIdentifier: ").append(toIndentedString(internalIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
