/*
 * FINBOURNE Identity Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1598
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.identity.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AgreementResponse
 */
public class AgreementResponseTest {
    private final AgreementResponse model = new AgreementResponse();

    /**
     * Model tests for AgreementResponse
     */
    @Test
    public void testAgreementResponse() {
        // TODO: test AgreementResponse
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'signedBy'
     */
    @Test
    public void signedByTest() {
        // TODO: test signedBy
    }

    /**
     * Test the property 'signedAt'
     */
    @Test
    public void signedAtTest() {
        // TODO: test signedAt
    }

}
