/*
 * FINBOURNE Identity Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1598
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.identity.model;

import com.finbourne.identity.model.Link;
import com.finbourne.identity.model.SupportAccessExpiry;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AuthenticationInformation
 */
public class AuthenticationInformationTest {
    private final AuthenticationInformation model = new AuthenticationInformation();

    /**
     * Model tests for AuthenticationInformation
     */
    @Test
    public void testAuthenticationInformation() {
        // TODO: test AuthenticationInformation
    }

    /**
     * Test the property 'issuerUrl'
     */
    @Test
    public void issuerUrlTest() {
        // TODO: test issuerUrl
    }

    /**
     * Test the property 'samlIdentityProviderId'
     */
    @Test
    public void samlIdentityProviderIdTest() {
        // TODO: test samlIdentityProviderId
    }

    /**
     * Test the property 'support'
     */
    @Test
    public void supportTest() {
        // TODO: test support
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
