/*
 * FINBOURNE Identity Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1598
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.identity.model;

import com.finbourne.identity.model.CreateUserRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateDomainRequest
 */
public class CreateDomainRequestTest {
    private final CreateDomainRequest model = new CreateDomainRequest();

    /**
     * Model tests for CreateDomainRequest
     */
    @Test
    public void testCreateDomainRequest() {
        // TODO: test CreateDomainRequest
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'technicalContact'
     */
    @Test
    public void technicalContactTest() {
        // TODO: test technicalContact
    }

    /**
     * Test the property 'billingContact'
     */
    @Test
    public void billingContactTest() {
        // TODO: test billingContact
    }

    /**
     * Test the property 'signedAgreements'
     */
    @Test
    public void signedAgreementsTest() {
        // TODO: test signedAgreements
    }

}
