/*
 * FINBOURNE Identity Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1598
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.identity.api;

import com.finbourne.identity.ApiException;
import com.finbourne.identity.model.AuthenticationInformation;
import com.finbourne.identity.model.LusidProblemDetails;
import com.finbourne.identity.model.LusidValidationProblemDetails;
import com.finbourne.identity.model.SupportAccessRequest;
import com.finbourne.identity.model.SupportAccessResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Ignore
public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    
    /**
     * GetAuthenticationInformation: Gets AuthenticationInformation
     *
     * Get the AuthenticationInformation associated with the current domain. This includes all the  necessary information to login to this domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAuthenticationInformationTest() throws ApiException {
        AuthenticationInformation response = api.getAuthenticationInformation();

        // TODO: test validations
    }
    
    /**
     * [EARLY ACCESS] GetSupportAccessHistory: Get the history of all support access granted and any information pertaining to their termination
     *
     * The active and inactive support requests will be returned, inactive support requests will have information pertaining to their termination  including obfuscated userIds of those who created and terminated the request
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSupportAccessHistoryTest() throws ApiException {
        List<SupportAccessResponse> response = api.getSupportAccessHistory();

        // TODO: test validations
    }
    
    /**
     * [EARLY ACCESS] GrantSupportAccess: Grants FINBOURNE support access to your account
     *
     * Granting support access will allow FINBOURNE employees full access to your data with the express intent to investigate support issues  You can revoke this (and all) access at any time using the InvalidateSupportAccess endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void grantSupportAccessTest() throws ApiException {
        SupportAccessRequest supportAccessRequest = null;
        SupportAccessResponse response = api.grantSupportAccess(supportAccessRequest);

        // TODO: test validations
    }
    
    /**
     * [EARLY ACCESS] InvalidateSupportAccess: Revoke any FINBOURNE support access to your account
     *
     * This will result in a loss of access to your data for all FINBOURNE support agents
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invalidateSupportAccessTest() throws ApiException {
        List<SupportAccessResponse> response = api.invalidateSupportAccess();

        // TODO: test validations
    }
    
}
