/*
 * FINBOURNE Identity Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1598
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.identity.api;

import com.finbourne.identity.ApiException;
import com.finbourne.identity.model.LusidProblemDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokensApi
 */
@Ignore
public class TokensApiTest {

    private final TokensApi api = new TokensApi();

    
    /**
     * [EARLY ACCESS] InvalidateToken: Invalidate current JWT token (sign out)
     *
     * Log the current user out of all Finbourne platforms by invalidating the current token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invalidateTokenTest() throws ApiException {
        api.invalidateToken();

        // TODO: test validations
    }
    
}
